networks:
    localnet:
        external: true
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - localnet
  postgres:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: hoteluser
      POSTGRES_PASSWORD: hotelpassword
      POSTGRES_DB: hoteldb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
