import {
    WifiHighIcon,
    BathtubIcon,
    BedIcon,
    TreeIcon,
    FlowerIcon,
    WavesIcon,
    LeafIcon,
    ClockIcon,
    WarningIcon,
    InfoIcon,
    CheckCircleIcon,
    IdentificationCardIcon,
    SpeakerHighIcon,
    PawPrintIcon,
    ArmchairIcon,
    ForkKnifeIcon,
    PintGlassIcon,
    BowlFoodIcon,
    CoffeeIcon,
    BrandyIcon,
    IceCreamIcon,
    CookieIcon,
    BowlSteamIcon,
    FishIcon,
    CookingPotIcon,
    OnigiriIcon,
    BuildingIcon,
    UsersThreeIcon,
    HeartIcon,
    ChairIcon,
    ToiletIcon,
    BroomIcon,
    LetterCirclePIcon,
    VideoCameraIcon,
    MicrophoneIcon,
    PaletteIcon,
} from "@phosphor-icons/react";
import type { IconWeight } from "@phosphor-icons/react";

export type FacilityIcon = {
    value: string;
    label: string;
    icon: React.ElementType;
    color: string;
    weight: IconWeight;
};

export const FACILITY_ICONS: FacilityIcon[] = [
    { value: "WifiHighIcon", label: "WiFi", icon: WifiHighIcon, color: "#3B82F6", weight: "fill" },
    { value: "LeafIcon", label: "Daun", icon: LeafIcon, color: "#22C55E", weight: "fill" },
    { value: "BathtubIcon", label: "Bathtub", icon: BathtubIcon, color: "#06B6D4", weight: "fill" },
    { value: "BedIcon", label: "Tempat Tidur", icon: BedIcon, color: "#8B5CF6", weight: "fill" },
    { value: "TreeIcon", label: "Pohon", icon: TreeIcon, color: "#16A34A", weight: "fill" },
    { value: "FlowerIcon", label: "Bunga", icon: FlowerIcon, color: "#EC4899", weight: "fill" },
    { value: "WavesIcon", label: "Kolam Renang", icon: WavesIcon, color: "#0EA5E9", weight: "fill" },
    { value: "ClockIcon", label: "Jam", icon: ClockIcon, color: "#F59E0B", weight: "fill" },
    { value: "WarningIcon", label: "Warning", icon: WarningIcon, color: "#EF4444", weight: "fill" },
    { value: "InfoIcon", label: "Info", icon: InfoIcon, color: "#6366F1", weight: "fill" },
    { value: "CheckCircleIcon", label: "Check", icon: CheckCircleIcon, color: "#10B981", weight: "fill" },
    { value: "IdentificationCardIcon", label: "ID Card", icon: IdentificationCardIcon, color: "#64748B", weight: "fill" },
    { value: "SpeakerHighIcon", label: "Sound", icon: SpeakerHighIcon, color: "#F97316", weight: "fill" },
    { value: "PawPrintIcon", label: "Pet", icon: PawPrintIcon, color: "#A855F7", weight: "fill" },
    { value: "ArmchairIcon", label: "Terrace", icon: ArmchairIcon, color: "#84CC16", weight: "fill" },
    { value: "ForkKnifeIcon", label: "Dapur", icon: ForkKnifeIcon, color: "#2d4d20", weight: "fill" },
    { value: "PintGlassIcon", label: "Minuman", icon: PintGlassIcon, color: "#2d4d20", weight: "fill" },
    { value: "BowlFoodIcon", label: "Makanan", icon: BowlFoodIcon, color: "#2d4d20", weight: "fill" },
    { value: "CoffeeIcon", label: "Kopi", icon: CoffeeIcon, color: "#2d4d20", weight: "fill" },
    { value: "BrandyIcon", label: "Brandy", icon: BrandyIcon, color: "#2d4d20", weight: "fill" },
    { value: "IceCreamIcon", label: "Ice Cream", icon: IceCreamIcon, color: "#2d4d20", weight: "fill" },
    { value: "CookieIcon", label: "Kue", icon: CookieIcon, color: "#2d4d20", weight: "fill" },
    { value: "BowlSteamIcon", label: "Sup", icon: BowlSteamIcon, color: "#2d4d20", weight: "fill" },
    { value: "FishIcon", label: "Ikan", icon: FishIcon, color: "#2d4d20", weight: "fill" },
    { value: "CookingPotIcon", label: "Panci Masak", icon: CookingPotIcon, color: "#2d4d20", weight: "fill" },
    { value: "OnigiriIcon", label: "Onigiri", icon: OnigiriIcon, color: "#2d4d20", weight: "fill" },
    { value: "BuildingIcon", label: "Gedung", icon: BuildingIcon, color: "#2d4d20", weight: "fill" },
    { value: "UsersThreeIcon", label: "Grup", icon: UsersThreeIcon, color: "#2d4d20", weight: "fill" },
    { value: "HeartIcon", label: "Hati", icon: HeartIcon, color: "#2d4d20", weight: "fill" },
    { value: "ChairIcon", label: "Kursi", icon: ChairIcon, color: "#2d4d20", weight: "fill" },
    { value: "ToiletIcon", label: "Toilet", icon: ToiletIcon, color: "#2d4d20", weight: "fill" },
    { value: "BroomIcon", label: "Sapu", icon: BroomIcon, color: "#2d4d20", weight: "fill" },
    { value: "LetterCirclePIcon", label: "Parkir", icon: LetterCirclePIcon, color: "#2d4d20", weight: "fill" },
    { value: "VideoCameraIcon", label: "Kamera Video", icon: VideoCameraIcon, color: "#2d4d20", weight: "fill" },
    { value: "MicrophoneIcon", label: "Mikrofon", icon: MicrophoneIcon, color: "#2d4d20", weight: "fill" },
    { value: "PaletteIcon", label: "Palet", icon: PaletteIcon, color: "#2d4d20", weight: "fill" },
];