-- Table structure for events
CREATE TABLE IF NOT EXISTS `events` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title_ind` VARCHAR(255) NOT NULL,
  `title_eng` VARCHAR(255) NOT NULL,
  `tagline_ind` VARCHAR(500) DEFAULT NULL,
  `tagline_eng` VARCHAR(500) DEFAULT NULL,
  `short_description_ind` TEXT DEFAULT NULL,
  `short_description_eng` TEXT DEFAULT NULL,
  `description_ind` TEXT DEFAULT NULL COMMENT 'JSON array of paragraphs',
  `description_eng` TEXT DEFAULT NULL COMMENT 'JSON array of paragraphs',
  `thumbnail` VARCHAR(500) DEFAULT NULL,
  `slug` VARCHAR(255) NOT NULL UNIQUE,
  `event_date` DATE NOT NULL,
  `event_time` VARCHAR(50) DEFAULT NULL,
  `location` VARCHAR(255) DEFAULT NULL,
  `capacity` INT(11) DEFAULT 0,
  `price` DECIMAL(15,2) DEFAULT 0.00,
  `included_items_ind` TEXT DEFAULT NULL COMMENT 'JSON array of included items',
  `included_items_eng` TEXT DEFAULT NULL COMMENT 'JSON array of included items',
  `requirements_ind` TEXT DEFAULT NULL COMMENT 'JSON array of requirements',
  `requirements_eng` TEXT DEFAULT NULL COMMENT 'JSON array of requirements',
  `gallery_images` TEXT DEFAULT NULL COMMENT 'JSON array of image URLs',
  `is_active` TINYINT(1) DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_slug` (`slug`),
  INDEX `idx_event_date` (`event_date`),
  INDEX `idx_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Sample data (optional - based on your existing events)
INSERT INTO `events` (
  `title_ind`, `title_eng`,
  `tagline_ind`, `tagline_eng`,
  `short_description_ind`, `short_description_eng`,
  `description_ind`, `description_eng`,
  `thumbnail`, `slug`, `event_date`, `event_time`, `location`, `capacity`, `price`,
  `included_items_ind`, `included_items_eng`,
  `requirements_ind`, `requirements_eng`,
  `gallery_images`
) VALUES
(
  'Upacara Pernikahan Jawa',
  'Javanese Wedding Ceremony',
  'Upacara pernikahan tradisional Jawa di pendopo kami yang indah',
  'Traditional Javanese wedding ceremony in our beautiful pendopo',
  'Upacara pernikahan tradisional Jawa di pendopo kami yang indah dengan musik gamelan',
  'Traditional Javanese wedding ceremony in our beautiful pendopo with gamelan music',
  '["Rasakan keindahan abadi upacara pernikahan tradisional Jawa di Rumah Budaya Tembi. Pendopo bersejarah kami memberikan latar belakang sempurna untuk hari istimewa Anda, menggabungkan elemen budaya otentik dengan kenyamanan modern.", "Upacara ini mencakup musik gamelan tradisional, koordinator pernikahan profesional, dan dekorasi venue lengkap dengan gaya Jawa klasik. Tim berpengalaman kami akan memandu Anda melalui setiap langkah ritual tradisional.", "Pendopo yang luas dapat menampung hingga 150 tamu, dengan area taman tambahan tersedia untuk resepsi koktail. Kami menawarkan paket yang dapat disesuaikan untuk visi dan anggaran Anda."]',
  '["Experience the timeless beauty of a traditional Javanese wedding ceremony at Tembi Cultural House. Our historic pendopo provides the perfect backdrop for your special day, combining authentic cultural elements with modern comforts.", "The ceremony includes traditional gamelan music, professional wedding coordinators, and full venue decoration in classic Javanese style. Our experienced team will guide you through every step of the traditional rituals.", "The spacious pendopo can accommodate up to 150 guests, with additional garden areas available for cocktail receptions. We offer customizable packages to suit your vision and budget."]',
  'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=2000&auto=format&fit=crop',
  'javanese-wedding-ceremony',
  '2025-06-15',
  '09:00 - 17:00',
  'Main Pendopo',
  150,
  25000000,
  '["Sewa venue (sepanjang hari)", "Ensemble gamelan tradisional", "Koordinator pernikahan", "Dekorasi Jawa", "Katering untuk 150 tamu", "Dokumentasi foto & video", "Ruang persiapan pengantin", "Parkir tamu"]',
  '["Venue rental (full day)", "Traditional gamelan ensemble", "Wedding coordinator", "Javanese decoration", "Catering for 150 guests", "Photo & video documentation", "Bridal preparation room", "Guest parking"]',
  '["Pemesanan harus dilakukan minimal 3 bulan sebelumnya", "Uang muka 50% diperlukan saat pemesanan", "Jumlah tamu final harus dikonfirmasi 2 minggu sebelum acara", "Acara harus selesai pukul 22:00"]',
  '["Booking must be made at least 3 months in advance", "Down payment of 50% required upon booking", "Final guest count must be confirmed 2 weeks before event", "Event must conclude by 22:00"]',
  '["https://images.unsplash.com/photo-1606800052052-a08af7148866?q=80&w=2000&auto=format&fit=crop", "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=2000&auto=format&fit=crop", "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=2000&auto=format&fit=crop", "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?q=80&w=2000&auto=format&fit=crop"]'
),
(
  'Workshop Musik Gamelan',
  'Gamelan Music Workshop',
  'Pelajari gamelan tradisional Jawa dari musisi master',
  'Learn traditional Javanese gamelan from master musicians',
  'Pelajari seni musik gamelan tradisional Jawa dari musisi master',
  'Learn the art of traditional Javanese gamelan music from master musicians',
  '["Temukan dunia musik gamelan yang mempesona dalam workshop immersive 3 jam yang dipimpin oleh musisi master. Pelajari tentang sejarah, signifikansi budaya, dan teknik bermain seni kuno Indonesia ini.", "Workshop praktis ini cocok untuk semua level, dari pemula hingga yang memiliki pengalaman musik. Anda akan belajar memainkan melodi dasar pada berbagai instrumen gamelan termasuk saron, bonang, dan kendang.", "Workshop ini mencakup istirahat makanan ringan tradisional Jawa dan diakhiri dengan pertunjukan grup di mana peserta bermain bersama sebagai ensemble."]',
  '["Discover the enchanting world of gamelan music in this immersive 3-hour workshop led by master musicians. Learn about the history, cultural significance, and playing techniques of this ancient Indonesian art form.", "This hands-on workshop is suitable for all levels, from complete beginners to those with some musical experience. You will learn to play basic melodies on various gamelan instruments including the saron, bonang, and kendang.", "The workshop includes a traditional Javanese snack break and concludes with a group performance where participants play together as an ensemble."]',
  'https://images.unsplash.com/photo-1511192336575-5a79af67a629?q=80&w=2000&auto=format&fit=crop',
  'gamelan-music-workshop',
  '2025-05-20',
  '14:00 - 17:00',
  'Cultural Hall',
  30,
  250000,
  '["Instruksi ahli", "Semua instrumen disediakan", "Makanan ringan & minuman tradisional", "Sertifikat workshop", "Materi pembelajaran untuk dibawa pulang", "Kesempatan foto dengan pakaian tradisional"]',
  '["Expert instruction", "All instruments provided", "Traditional snacks & drinks", "Workshop certificate", "Take-home learning materials", "Photo opportunities in traditional attire"]',
  '["Tidak diperlukan pengalaman musik sebelumnya", "Usia minimum: 12 tahun", "Pakaian nyaman direkomendasikan", "Datang 15 menit sebelum workshop dimulai"]',
  '["No prior musical experience required", "Minimum age: 12 years old", "Comfortable clothing recommended", "Arrive 15 minutes before workshop starts"]',
  '["https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?q=80&w=2000&auto=format&fit=crop", "https://images.unsplash.com/photo-1511192336575-5a79af67a629?q=80&w=2000&auto=format&fit=crop", "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2000&auto=format&fit=crop", "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?q=80&w=2000&auto=format&fit=crop"]'
);
